### ISSUE TITLE
Concurrent modification exception on startup

### ISSUE THREAD

**Issue by lorenzop** [Aeltumn/automated_crafting#10]
in the file RecipeLoader, does this need to run asynchronously? it seems maybe there is little benefit to being async, so maybe something like this could fix the problem?

```
    public RecipeLoader(final AutomatedCrafting inst) {
        this.instance=inst;
        //We load the recipes once on start, this is all we do on 1.12.
        Bukkit.getScheduler().runTask(
            inst,
            new Runnable() {
                public void run() {
                    reload(null);
                }
            }
        );
    }
```

here is the exception I got when the plugin loaded:

```
[22:33:01] [Server thread/WARN]: [AutomatedCrafting] Task #16 for AutomatedCrafting v1.12/1.14-2.2.1 generated an exception
java.util.ConcurrentModificationException: java.util.ConcurrentModificationException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_242]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_242]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_242]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_242]
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593) ~[?:1.8.0_242]
        at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677) ~[?:1.8.0_242]
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735) ~[?:1.8.0_242]
        at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:714) ~[?:1.8.0_242]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:1.8.0_242]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[?:1.8.0_242]
        at nl.dgoossens.autocraft.RecipeLoader.getRecipesFor(RecipeLoader.java:61) ~[?:?]
        at nl.dgoossens.autocraft.MainDropperTick.lambda$run$3(MainDropperTick.java:50) ~[?:?]
        at java.util.Collection.removeIf(Collection.java:414) ~[?:1.8.0_242]
        at nl.dgoossens.autocraft.MainDropperTick.run(MainDropperTick.java:44) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.15.2.jar:git-Spigot-2040c4c-1872231]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) [spigot-1.15.2.jar:git-Spigot-2040c4c-1872231]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036) [spigot-1.15.2.jar:git-Spigot-2040c4c-1872231]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406) [spigot-1.15.2.jar:git-Spigot-2040c4c-1872231]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [spigot-1.15.2.jar:git-Spigot-2040c4c-1872231]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [spigot-1.15.2.jar:git-Spigot-2040c4c-1872231]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.util.ConcurrentModificationException
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1561) ~[?:1.8.0_242]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_242]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_242]
        at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:747) ~[?:1.8.0_242]
        at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:721) ~[?:1.8.0_242]
        at java.util.stream.AbstractTask.compute(AbstractTask.java:327) ~[?:1.8.0_242]
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) ~[?:1.8.0_242]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_242]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_242]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_242]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_242]
[22:33:01] [Craft Scheduler Thread - 1/INFO]: [AutomatedCrafting] Finished reloading 583 recipes, took 4495 ms...
```

**Comment by Aeltumn** [comment]
I don't think this error is due to the code being ran asynchronously. I'll probably look into this further for the next big update, but that might not be anytime soon.

**Comment by Aeltumn** [comment]
Fixed in next update!
