### ISSUE TITLE
Throws Errors in 1.17

### ISSUE THREAD

**Issue by Strahilchu** [Aeltumn/automated_crafting#25]
**Describe the bug**
[09:08:04] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Class.newInstance()" because "nl.dgoossens.autocraft.helpers.SerializedItem.nbtTagCompound" is null
[09:08:04] [Server thread/WARN]: 	at nl.dgoossens.autocraft.helpers.SerializedItem.build(SerializedItem.java:105)
[09:08:04] [Server thread/WARN]: 	at nl.dgoossens.autocraft.helpers.SerializedItem.<init>(SerializedItem.java:43)
[09:08:04] [Server thread/WARN]: 	at nl.dgoossens.autocraft.CrafterRegistryImpl.forceSave(CrafterRegistryImpl.java:239)
[09:08:04] [Server thread/WARN]: 	at nl.dgoossens.autocraft.AutomatedCrafting.onDisable(AutomatedCrafting.java:52)
[09:08:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[09:08:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405)
[09:08:04] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533)
[09:08:04] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:519)
[09:08:04] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:512)
[09:08:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.disablePlugins(CraftServer.java:452)
[09:08:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.stop(MinecraftServer.java:951)
[09:08:04] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.stop(DedicatedServer.java:804)
[09:08:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1230)
[09:08:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[09:08:04] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831).

**To Reproduce**
1. Setup an autocrafter
2. Put anything in it.
3. Watch console get spammed each time it crafts

**Expected behavior**
No error

**Version Information**
What Minecraft/Bukkit version are you running? 
1.17
What version of Automated Crafting are you using?
2.4
What versions of dependencies (like CustomCrafting) are being used?
None

**Comment by Apprisco** [comment]
[02:56:47 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Constructor.newInstance(Object[])" because "nl.dgoossens.autocraft.api.CraftingRecipe.itemConstructor" is null
[02:56:47 WARN]:        at nl.dgoossens.autocraft.api.CraftingRecipe.getContainerItem(CraftingRecipe.java:64)
[02:56:47 WARN]:        at nl.dgoossens.autocraft.helpers.BukkitRecipe.lambda$takeMaterials$11(BukkitRecipe.java:240)
[02:56:47 WARN]:        at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1694)
[02:56:47 WARN]:        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
[02:56:47 WARN]:        at nl.dgoossens.autocraft.helpers.BukkitRecipe.takeMaterials(BukkitRecipe.java:233)
[02:56:47 WARN]:        at nl.dgoossens.autocraft.MainCrafterTick.lambda$run$0(MainCrafterTick.java:77)
[02:56:47 WARN]:        at java.base/java.util.Optional.ifPresent(Optional.java:178)
[02:56:47 WARN]:        at nl.dgoossens.autocraft.MainCrafterTick.run(MainCrafterTick.java:36)
[02:56:47 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100)
[02:56:47 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[02:56:47 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1562)
[02:56:47 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:490)
[02:56:47 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1477)
[02:56:47 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1261)
[02:56:47 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[02:56:47 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

Getting a different error on my side.

**Comment by Aeltumn** [comment]
Will be fixed in the next update.
